# Generated by Django 5.1.2 on 2024-11-23 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_fare_delete_batt_delete_gscoordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fare',
            old_name='Route',
            new_name='RouteEnd',
        ),
        migrations.AddField(
            model_name='fare',
            name='RouteStart',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
