# Generated by Django 5.1.2 on 2024-11-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_route_fare_routeend_fare_routestart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fare',
            old_name='RouteEnd',
            new_name='route_end',
        ),
        migrations.RenameField(
            model_name='fare',
            old_name='RouteStart',
            new_name='route_start',
        ),
    ]
