# Generated by Django 5.1.2 on 2024-11-23 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_routeend_fare_route_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='route_id',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
