# Generated by Django 5.1.2 on 2024-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_fare_route_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('route_start', models.CharField(max_length=100)),
                ('route_end', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('passenger_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
