# Generated by Django 5.1.2 on 2024-11-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='passenger_count',
            new_name='passengerCount',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='route_end',
            new_name='routeEnd',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='route_start',
            new_name='routeStart',
        ),
    ]
